### PR TITLE
Fixed first mx link

### PR DESCRIPTION
**Pull request by perfaram**

### CODE REVIEW

**Comment by zhiayang** [comment]
Huh, why would you change this? My github profile is indeed at https://github.com/zhiayang, not requimrar...

**Comment by perfaram** [comment]
Sry, but then why is the second link to mx pointing to requimrar ? Moreover, the first link is broken.

**Comment by zhiayang** [comment]
My mistake, the second link is the wrong one. I did notice the first link is broken, but I suspect it's because it was being treated as a relative link, and the `https://` bit fixes that problem.

**Comment by perfaram** [comment]
So it should be OK now :+1:

**Pull request closed without merging**
